esphome:
  name: $device_name
  friendly_name: $friendly_name

logger:
  level: DEBUG
  # baud_rate: 0

wifi:
  id: wifi_id
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password

  ap:
    ssid: "${friendly_name}"
    password: "12345678"

web_server:
  version: 3
  port: 80

captive_portal:
  id: captive_portal_id

improv_serial:

time:
  - platform: homeassistant
    id: esp_time

ota:
  - platform: esphome
    # password: !secret ota_password

api:

sensor:
  - platform: uptime
    name: Uptime
    type: timestamp

  - platform: wifi_signal
    name: "WiFi - Signal"

debug:

text_sensor:
  - platform: version
    name: "ESPHome Version"

  - platform: debug
    reset_reason:
      name: "Reset Reason"

  - platform: wifi_info
    ip_address:
      id: wifi_ip
      name: WiFi - IP
    ssid:
      id: wifi_ssid
      name: WiFi - SSID
    mac_address:
      name: WiFi - Mac Address
    dns_address:
      name: WiFi - DNS Address

button:
  - platform: restart
    name: "Restart"
    id: restart_btn

  - platform: factory_reset
    id: factory_reset_btn
    name: "Factory Reset"
